data = "./weights/embeddings/"
mode = "text_embedding"
[wandb]
mode = "online" # "online", "offline", "disabled"
entity = "piercus"
project = "color-palette"
name = "wpalette-txt-emb-expe"
tags = ["weighted-palette", "embeddings"]

[sd]
unet = "weights/models/unet.safetensors"
text_encoder = "weights/models/CLIPTextEncoderL.safetensors"
lda = "weights/models/lda.safetensors"

[latent_diffusion]
unconditional_text_sampling_probability = 1.0
unconditional_input_sampling_probability = 0.0
offset_noise = 0.1

[palette_encoder]
max_colors = 8
feedforward_dim = 128
num_layers = 0
mode = 'mlp'
embedding_dim = 768
weighted_palette = false

[training]
duration = "10000:epoch"
seed = 0
batch_size = 20
gradient_accumulation = "10:step"
# clip_grad_norm = 1.0
# clip_grad_value = 1.0
evaluation_interval = "2:epoch"
evaluation_seed = 1
# num_workers = 8
# use_color_loss = false
device="cuda:0"
dtype="bfloat16"

[monitor_gradient]
patterns = ["ip_adapter.*"]

[optimizer]
optimizer = "AdamW" # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
learning_rate = 1e-4
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[lr_scheduler]
type = "ConstantLR"
update_interval = "1:step"
warmup = "500:step"

[dataset]
hf_repo = "refiners/unsplash-25k-cogvlm-captions"
revision = "main"
resize_image_max_size = 512
split = "train[200:1200]"

[eval_dataset]
hf_repo = "refiners/unsplash-25k-cogvlm-captions"
revision = "main"
resize_image_max_size = 512
split = "train[200:250]"

[offload_to_cpu]
use = true

[grid_evaluation]
use = false

[visual_evaluation]
batch_size = 25
condition_scale = 1.0
db_indexes=[0, 1, 2, 3, 4, 5]
use = true

[mmd_evaluation]
batch_size = 12
condition_scale = 1.0
use = true

[timestep_loss_rescaler]
use = true